# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

name: foundation

version: 0.0.1

publish_to: "none"

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  collection: ^1.19.1
  characters: ^1.3.0
  http: ^1.2.0

  image: ^4.1.3

#  stdlibc # FFI-based std. lib. of c-lang.
  dart_lmdb2: ^0.9.7 # FFI-based LMDB abstraction

  sqlite3: ^2.1.0
  sqlite_async: ^0.11.4

  flutter:
    sdk: flutter

  path_provider: ^2.1.3

  intl: 0.20.2

  cupertino_icons: ^1.0.6

  flutter_animate: ^4.5.0

#  forui # by forus-labs # beautiful component-collection with icons
#  skeletonizer # auto. shimmer effect for widgets
#  bootstrap_icons:
#  cyclop:
#  carousel_slider:
#  smooth_page_indicator: # "Scrolling dots" effect, with `carousel_slider`


flutter:

  uses-material-design: true

#  assets:
#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg
#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Bold.ttf
#          weight: 700
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
